---
sudo: required
dist: trusty

# Test on PHP7
language: php
php:
  - '7.1'
  - nightly

matrix:
  allow_failures:
    - php: nightly
  fast_finish: true

env:
  matrix:
    - DB=mysql
    - DB=sqlite
    - DB=postgresql

# Cache composer dependencies
cache:
  directories:
    - vendor

addons:
  postgresql: "9.6"
      
services:
  - mysql
  - redis-server
  - postgresql
  - docker

before_install:
  # Install dependencies
  - chmod a+x tests/.travis/install_dependencies.sh
  - bash tests/.travis/install_dependencies.sh
  - pecl install libsodium-2.0.2
  # Spin up docker contains to supplement services
  - docker run -d -p 1025:1025 mailhog/mailhog
  - docker run -d -p 7711:7711 charlesportwoodii/xenial:disque
  # Check the installed PHP modules
  - php -m

# Install the CLI tasks
install:
  - phpenv config-rm xdebug.ini || true
  - sh -c "if [ '$DB' = 'mysql' ]; then mysql -u root -e 'CREATE DATABASE IF NOT EXISTS root;'; cp tests/mysql-travis.yml config/config.yml; fi"
  - sh -c "if [ '$DB' = 'sqlite' ]; then cp tests/sqlite-travis.yml config/config.yml; fi"
  - sh -c "if [ '$DB' = 'postgresql' ]; then cp tests/postgresql-travis.yml config/config.yml; fi"
  - composer install -ovn --no-interaction --prefer-source
  - ./yii migrate/up --interactive=0

script:
  - ./vendor/bin/codecept run

after_script:
  - docker stop $(docker ps -a -q) -f
