---
sudo: true
dist: trusty

# Test on PHP7
language: php
php:
  - '7.1'
  - nightly

matrix:
  allow_failures:
    - php: nightly
  fast_finish: true

env:
  matrix:
    - DB=mysql
    - DB=sqlite
    - DB=postgresql

# Cache composer dependencies
cache:
  directories:
    - $HOME/disque
    - $HOME/libsodium-lib
    - vendor

addons:
  postgresql: "9.6"
      
services:
  - mysql
  - redis-server
  - postgresql

before_install:
  # Install Ruby 2.4.0
  - rvm install 2.4.0
  - rvm use 2.4.0
  - ruby --version
  # Install dependencies
  - chmod a+x tests/.travis/install_dependencies.sh
  - bash tests/.travis/install_dependencies.sh
  # Install MailCatcher
  - gem install mailcatcher
  - mailcatcher catchmail &2> /dev/null
  - /$HOME/disque/src/disque-server &2> /dev/null
  # Check the installed PHP modules
  - php -m
  - netstat -ant | grep tcp

# Install the CLI tasks
install:
  - phpenv config-rm xdebug.ini || true
  - sh -c "if [ '$DB' = 'mysql' ]; then mysql -u root -e 'CREATE DATABASE IF NOT EXISTS root;'; cp tests/mysql-travis.yml config/config.yml; fi"
  - sh -c "if [ '$DB' = 'sqlite' ]; then cp tests/sqlite-travis.yml config/config.yml; fi"
  - sh -c "if [ '$DB' = 'postgresql' ]; then cp tests/postgresql-travis.yml config/config.yml; fi"
  - composer install -ovn --no-interaction --prefer-source
  - ./yii migrate/up --interactive=0

script:
  - ./vendor/bin/codecept run
