---
# Allow for container based builds
sudo: false

# Test on PHP7
language: php
php:
  - '7.0'
  - '7.1'
  - nightly

matrix:
  allow_failures:
    - php: nightly
  fast_finish: true

env:
  matrix:
    - TEST_SUITE=unit DB=mysql
    - TEST_SUITE=api DB=mysql
    - TEST_SUITE=unit DB=sqlite
    - TEST_SUITE=api DB=sqlite

# Cache composer dependencies
cache:
  directories:
    #- $HOME/disque
    #- $HOME/libsodium/lib
    #- $HOME/libsodium-php/modules
    - vendor

services:
  - mysql
  - redis-server

before_install:
  # Install Ruby 2.4.0
  - rvm install 2.4.0
  - rvm use 2.4.0
  - ruby --version
  # Install dependencies
  - chmod a+x tests/.travis/install_dependencies.sh
  - bash tests/.travis/install_dependencies.sh
  # Install MailCatcher
  - gem install mailcatcher
  - mailcatcher catchmail &2> /dev/null

# Install the CLI tasks
install:
  - phpenv config-rm xdebug.ini
  - sh -c "if [ '$DB' = 'mysql' ]; then mysql -u root -e 'CREATE DATABASE IF NOT EXISTS root;'; cp tests/mysql-travis.yml config/config.yml; fi"
  - sh -c "if [ '$DB' = 'sqlite' ]; then cp tests/sqlite-travis.yml config/config.yml; fi"
  - composer install -ovn --no-interaction --prefer-source
  - ./yii migrate/up --interactive=0

before_script:
  - php -m
  - /$HOME/disque/src/disque-server &2> /dev/null

script:
  - ./vendor/bin/codecept run $TEST_SUITE
