version: "3.3"
services:
  nginx:
    image: charlesportwoodii/nginx:mainline
    ports:
      - "80:80"
      - "443:443"
    links:
      - php:php
    volumes:
      - ${PWD-.}:/var/www
      - ${PWD-.}/config/.docker/nginx/conf.d:/etc/nginx/conf/conf.d
      - ${PWD-.}/config/.docker/certs/server.crt:/etc/nginx/conf/ssl/server.crt
      - ${PWD-.}/config/.docker/certs/server.key:/etc/nginx/conf/ssl/server.key
  php:
    image: charlesportwoodii/php:7.1
    working_dir: /var/www
    links:
      - redis:redis
      - mailhog:mailhog
      - mariadb:mariadb
    volumes:
      - ${PWD-.}:/var/www
  rpq:
    image: charlesportwoodii/php:7.1
    entrypoint: >
      /bin/bash -lc "./vendor/bin/rpq queue -c /var/www/config/config.yml"
    working_dir: /var/www
    links:
      - redis:redis
      - mailhog:mailhog
      - mariadb:mariadb
    volumes:
      - ${PWD-.}:/var/www
  redis:
    image: redis:4.0-alpine
  mailhog: 
    image: mailhog/mailhog
    ports:
      - "8025:8025"
  mariadb:
    image: mariadb
    volumes:
      - mariadb:/var/lib/mysql
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=root
      - MYSQL_USER=local
      - MYSQL_PASSWORD=local

volumes:
  mariadb: