version: "3.3"
services:
  nginx:
    image: charlesportwoodii/xenial:nginx
    ports:
      - "80:80"
      - "443:443"
    links:
      - php:php
    volumes:
      - ./:/var/www
      - ./config/.docker/nginx/conf.d:/etc/nginx/conf/conf.d
  php:
    image: charlesportwoodii/xenial:php71
    working_dir: /var/www
    ports:
      - "9000:9000"
    links:
      - redis:redis
      - mailhog:mailhog
      - mariadb:mariadb
      - disque:disque
    volumes:
      - ./:/var/www
  redis:
    image: redis
    ports:
      - "6379:6379"
  mailhog: 
    image: mailhog/mailhog
    ports:
      - "8025:8025"
  mariadb:
    image: mariadb
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=root
      - MYSQL_USER=local
      - MYSQL_PASSWORD=local
  disque:
    image: charlesportwoodii/xenial:disque
