---
# Application specific configuration
app:
  id: "yii2-api"
  name: "Yii2 API Skeleton"
  debug: true
  env: 'dev'

# Database configuration
database:
  driver:
  database:
  host: 127.0.0.1
  username:
  password:
  schema: 'public'

# Redis Configuration
pid: ./runtime/rpq.pid

redis:
  host: redis
  port: 6379
  database: 0
  namespace: rpq

swiftmailer:
  host: mailhog
  port: 1025
  username: null
  password: null
  encryption: null

user: '\common\models\User'

access_control:
  header: null
  secret: null

log:
  logger: "/var/www/common/config/logs.php"
  level: "\\Monolog\\Logger::DEBUG"
  log_changes_to_database: false

queue:
  default:
    max_jobs: 20
    poll_interval: 100
    deadline_timeout: 100

process:
  script: './yii'
  command: 'worker/process'
  config: false
