---
# Application specific configuration
app:
  id: "yii2-api"
  name: "Yii2 API Skeleton"
  debug: true
  env: 'dev'

# Database configuration
database:
  driver:
  database:
  host: 127.0.0.1
  username:
  password:
  schema: 'public'

# Redis Configuration
pid: ./runtime/rpq.pid

redis:
  host: redis
  port: 6379
  database: 0
  namespace: rpq

swiftmailer:
  host: mailhog
  port: 1025
  username: null
  password: null
  encryption: null

user: '\app\models\User'

access_control:
  header: null
  secret: null

log:
  handler: "\\Monolog\\Handler\\StreamHandler"
  formatter: null
  persistent: null
  level: "\\Monolog\\Logger::DEBUG"
  connection_string: "../runtime/logs/application.log"
  categories:
    except:
      - 'yii\web\HttpException:400'
      - 'yii\web\HttpException:401'
      - 'yii\web\HttpException:403'
      - 'yii\web\HttpException:404'

queue:
  default:
    max_jobs: 20
    poll_interval: 100
    deadline_timeout: 100

process:
  script: './yii'
  command: 'worker/process'
  config: false
